# -*- coding: utf-8 -*-
from pathlib import Path

def u(s):
    return s.encode('utf-8').decode('unicode_escape') if '\\u' in s else s

# Built with explicit unicode escapes
T = []
a = T.append
a('<template>')
a('  <div class="app-container">')
a('    <el-form :model="queryParams" ref="queryForm" size="small" :inline="true" v-show="showSearch" label-width="90px">')
a('      <el-form-item label="\u60a3\u8005\u59d3\u540d" prop="patientName">')
a('        <el-input v-model="queryParams.patientName" placeholder="\u6a21\u7cca\u67e5\u8be2" clearable @keyup.enter.native="handleQuery" />')
a('      </el-form-item>')
a('      <el-form-item label="\u80f8\u7247ID" prop="imageId">')
a('        <el-input v-model="queryParams.imageId" placeholder="\u5f71\u50cfID" clearable @keyup.enter.native="handleQuery" />')
a('      </el-form-item>')
a('      <el-form-item label="\u56fe\u7247\u540d" prop="imageName">')
a('        <el-input v-model="queryParams.imageName" placeholder="\u6a21\u7cca\u67e5\u8be2" clearable @keyup.enter.native="handleQuery" />')
a('      </el-form-item>')
a('      <el-form-item>')
a('        <el-button type="primary" icon="el-icon-search" size="mini" @click="handleQuery">\u641c\u7d22</el-button>')
a('        <el-button icon="el-icon-refresh" size="mini" @click="resetQuery">\u91cd\u7f6e</el-button>')
a('      </el-form-item>')
a('    </el-form>')
a('')
a('    <el-row :gutter="10" class="mb8">')
a('      <el-col :span="1.5">')
a('        <el-button type="danger" plain icon="el-icon-delete" size="mini" :disabled="multiple" @click="handleDelete()" v-hasPermi="[\'ai:analysis:result:remove\']">\u5220\u9664</el-button>')
a('      </el-col>')
a('      <right-toolbar :showSearch.sync="showSearch" @queryTable="getList" />')
a('    </el-row>')
a('')
a('    <el-alert')
a('      title="\u5206\u6790\u8bb0\u5f55\u4ec5\u5728\u9605\u7247\u5668\u6216 AI \u5206\u6790\u5217\u8868\u6267\u884c\u300cAI \u75c5\u7076\u5206\u6790\u300d\u540e\u81ea\u52a8\u65b0\u589e\uff0c\u672c\u9875\u4e0d\u652f\u6301\u624b\u5de5\u65b0\u589e\u6216\u4fee\u6539\u3002"')
a('      type="info" :closable="false" show-icon class="mb8" />')
a('')
a('    <el-table v-loading="loading" :data="dataList" @selection-change="handleSelectionChange">')
a('      <el-table-column type="selection" width="55" align="center" />')
a('      <el-table-column label="\u8bb0\u5f55ID" prop="analysisId" width="90" align="center" />')
a('      <el-table-column label="\u80f8\u7247ID" prop="imageId" width="90" align="center" />')
a('      <el-table-column label="\u60a3\u8005" prop="patientName" min-width="100" show-overflow-tooltip />')
a('      <el-table-column label="\u56fe\u7247\u540d" prop="imageName" min-width="140" show-overflow-tooltip />')
a('      <el-table-column label="\u75c5\u7076\u6570" prop="lesionCount" width="80" align="center" />')
a('      <el-table-column label="\u611f\u67d3\u7387" width="90" align="center">')
a('        <template slot-scope="scope">{{ formatRate(scope.row.infectionRate) }}</template>')
a('      </el-table-column>')
a('      <el-table-column label="\u68c0\u6d4b\u6458\u8981" prop="detectDiagnosis" min-width="180" show-overflow-tooltip />')
a('      <el-table-column label="\u62a5\u544a\u65f6\u95f4" prop="reportCreateTime" width="160" align="center" />')
a('      <el-table-column label="\u5165\u5e93\u65f6\u95f4" prop="createTime" width="168" align="center">')
a('        <template slot-scope="scope">{{ parseTime(scope.row.createTime) }}</template>')
a('      </el-table-column>')
a('      <el-table-column label="\u64cd\u4f5c" align="center" width="140">')
a('        <template slot-scope="scope">')
a('          <el-button size="mini" type="text" icon="el-icon-view" @click="handleView(scope.row)" v-hasPermi="[\'ai:analysis:result:query\']">\u8be6\u60c5</el-button>')
a('          <el-button size="mini" type="text" icon="el-icon-delete" @click="handleDelete(scope.row)" v-hasPermi="[\'ai:analysis:result:remove\']">\u5220\u9664</el-button>')
a('        </template>')
a('      </el-table-column>')
a('    </el-table>')
a('')
a('    <pagination v-show="total > 0" :total="total" :page.sync="queryParams.pageNum" :limit.sync="queryParams.pageSize" @pagination="getList" />')
a('')
a('    <el-dialog title="\u5206\u6790\u7ed3\u679c\u8be6\u60c5" :visible.sync="viewOpen" width="920px" append-to-body destroy-on-close>')
a('      <template v-if="detail">')
a('        <el-descriptions :column="2" border size="small" class="mb12">')
a('          <el-descriptions-item label="\u8bb0\u5f55ID">{{ detail.analysisId }}</el-descriptions-item>')
a('          <el-descriptions-item label="\u80f8\u7247ID">{{ detail.imageId }}</el-descriptions-item>')
a('          <el-descriptions-item label="\u60a3\u8005">{{ detail.patientName || dash }}</el-descriptions-item>')
a('          <el-descriptions-item label="\u56fe\u7247\u540d">{{ detail.imageName || dash }}</el-descriptions-item>')
a('          <el-descriptions-item label="\u75c5\u7076\u6570\u91cf">{{ detail.lesionCount != null ? detail.lesionCount : dash }}</el-descriptions-item>')
a('          <el-descriptions-item label="\u611f\u67d3\u7387">{{ formatRate(detail.infectionRate) }}</el-descriptions-item>')
a('          <el-descriptions-item label="\u611f\u67d3\u9762\u79ef(px\u00b2)">{{ detail.totalInfectionArea != null ? detail.totalInfectionArea : dash }}</el-descriptions-item>')
a('          <el-descriptions-item label="\u62a5\u544a\u751f\u6210\u65f6\u95f4">{{ detail.reportCreateTime || dash }}</el-descriptions-item>')
a('          <el-descriptions-item label="\u68c0\u6d4b\u6458\u8981" :span="2">{{ detail.detectDiagnosis || dash }}</el-descriptions-item>')
a('        </el-descriptions>')
a('        <h4 class="detail-section-title">\u4e00\u3001\u75c5\u7076\u68c0\u6d4b\uff08YOLO\uff09</h4>')
a('        <pre class="mono-pre">{{ prettyJson(detail.detectResultJson) }}</pre>')
a('        <el-divider />')
a('        <h4 class="detail-section-title">\u4e8c\u3001AI \u5f71\u50cf\u8bca\u65ad\u62a5\u544a\uff08\u7ed3\u6784\u5316\uff09</h4>')
a('        <template v-if="reportStruct">')
a('          <el-card shadow="never" class="struct-card">')
a('            <motion class="struct-block">')
# fix motion in script output - use div variable
div = 'motion'
div = chr(100)+chr(105)+chr(118)
# rewrite last line - pop and fix
T.pop()
a('            <' + div + ' class="struct-block">')
a('              <h5>\u8bca\u65ad\u7ed3\u8bba</h5>')
a('              <p v-if="reportStruct.conclusion && reportStruct.conclusion.mainDiagnosis"><b>\u4e3b\u8981\u8bca\u65ad\uff1a</b>{{ reportStruct.conclusion.mainDiagnosis }}</p>')
a('              <p v-if="reportStruct.conclusion && reportStruct.conclusion.confidence"><b>\u8bca\u65ad\u7f6e\u4fe1\u5ea6\uff1a</b>{{ reportStruct.conclusion.confidence }}</p>')
a('              <p v-if="reportStruct.conclusion && reportStruct.conclusion.differentialDiagnosis"><b>\u9274\u522b\u8bca\u65ad\uff1a</b>{{ reportStruct.conclusion.differentialDiagnosis }}</p>')
a('            </' + div + '>')
a('            <' + div + ' class="struct-block" v-if="hasList(reportStruct.imagingAnalysis && reportStruct.imagingAnalysis.lesionFeatures)">')
a('              <h5>\u5f71\u50cf\u5b66\u5206\u6790 \u00b7 \u75c5\u7076\u7279\u5f81</h5>')
a('              <ul><li v-for="(t, i) in reportStruct.imagingAnalysis.lesionFeatures" :key="\'lf\'+i">{{ t }}</li></ul>')
a('            </' + div + '>')
a('            <' + div + ' class="struct-block" v-if="reportStruct.summary">')
a('              <h5>\u603b\u7ed3</h5><p>{{ reportStruct.summary }}</p>')
a('            </' + div + '>')
a('          </el-card>')
a('        </template>')
a('        <el-empty v-else description="\u65e0\u7ed3\u6784\u5316\u62a5\u544a\u6570\u636e" :image-size="48" />')
a('        <el-divider /><h4 class="detail-section-title">\u62a5\u544a\u539f\u6587</h4>')
a('        <pre class="mono-pre report-raw">{{ detail.diagnosisReportRaw || dash }}</pre>')
a('      </template>')
a('    </el-dialog>')
a('  </' + div + '>')
a('</template>')
a('')
a('<script>')
a("import { listAiAnalysisResult, getAiAnalysisResult, delAiAnalysisResult } from '@/api/medical/aiAnalysisResult'")
a('export default {')
a("  name: 'AiAnalysisResultManage',")
a('  data() { return { dash: "\u2014", loading: true, showSearch: true, total: 0, dataList: [], ids: [], multiple: true,')
a('    queryParams: { pageNum: 1, pageSize: 10, patientName: undefined, imageId: undefined, imageName: undefined },')
a('    viewOpen: false, detail: null, reportStruct: null } },')
a('  created() { this.getList() },')
a('  methods: {')
a('    getList() { this.loading = true; listAiAnalysisResult(this.queryParams).then(res => {')
a('      this.dataList = res.rows || []; this.total = res.total || 0; this.loading = false }).catch(() => { this.loading = false }) },')
a('    handleQuery() { this.queryParams.pageNum = 1; this.getList() },')
a("    resetQuery() { this.resetForm('queryForm'); this.handleQuery() },")
a('    handleSelectionChange(s) { this.ids = s.map(i => i.analysisId); this.multiple = !s.length },')
a('    handleView(row) { getAiAnalysisResult(row.analysisId).then(res => {')
a('      this.detail = res.data || res; this.reportStruct = null')
a('      if (this.detail && this.detail.diagnosisReportJson) { try { this.reportStruct = JSON.parse(this.detail.diagnosisReportJson) } catch (e) {} }')
a('      this.viewOpen = true }) },')
a('    handleDelete(row) { const ids = row && row.analysisId ? [row.analysisId] : this.ids')
a('      if (!ids.length) return; this.$modal.confirm("\u662f\u5426\u786e\u8ba4\u5220\u9664\u9009\u4e2d\u7684\u5206\u6790\u8bb0\u5f55\uff1f").then(() => delAiAnalysisResult(ids.join(","))).then(() => { this.getList(); this.$modal.msgSuccess("\u5220\u9664\u6210\u529f") }).catch(() => {}) },')
a("    formatRate(val) { if (val == null || val === '') return this.dash; const n = Number(val); return Number.isNaN(n) ? val : n + '%' },")
a('    prettyJson(str) { if (!str) return this.dash; try { return JSON.stringify(JSON.parse(str), null, 2) } catch (e) { return str } },')
a('    hasList(arr) { return Array.isArray(arr) && arr.length > 0 }')
a('  }')
a('}')
a('</script>')
a('<style scoped>')
a('.mb12{margin-bottom:12px}.mb8{margin-bottom:8px}')
a('.detail-section-title{margin:12px 0 8px;font-size:14px;font-weight:600;color:#303133}')
a('.mono-pre{margin:0;padding:10px;background:#fafafa;border:1px solid #ebeef5;border-radius:6px;font-size:12px;line-height:1.55;white-space:pre-wrap;word-break:break-word;max-height:240px;overflow:auto}')
a('.report-raw{max-height:320px}.struct-card{background:#fcfcfc}.struct-block{margin-bottom:12px}')
a('</style>')

path = Path(__file__).resolve().parents[1] / 'ruoyi-ui/src/views/medical/ai-analysis-result/index.vue'
path.parent.mkdir(parents=True, exist_ok=True)
path.write_text('\n'.join(T), encoding='utf-8')
print('written', path)
